# Generated by Django 5.0.3 on 2024-03-25 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('Full_name', models.CharField(max_length=256)),
                ('Date_of_birth', models.DateField()),
                ('SIN', models.CharField(max_length=20)),
                ('Date_of_hire', models.DateField()),
                ('Address', models.CharField(max_length=256)),
                ('City', models.CharField(max_length=256)),
                ('Zip', models.CharField(max_length=256)),
                ('State', models.CharField(max_length=256)),
                ('Home_phone', models.CharField(max_length=20)),
                ('Cell_phone', models.CharField(max_length=20)),
                ('Spouse_name', models.CharField(max_length=256)),
                ('Em_name', models.CharField(max_length=256)),
                ('Em_relationship', models.CharField(max_length=256)),
                ('Date', models.DateField()),
            ],
        ),
    ]
